"""empty message

Revision ID: 5fe110ca29e7
Revises: 04e6148ab996
Create Date: 2018-06-18 17:42:59.740765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fe110ca29e7'
down_revision = '04e6148ab996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Request', sa.Column('type_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('Request_request_id_fkey', 'Request', type_='foreignkey')
    op.create_foreign_key(None, 'Request', 'Request_type', ['type_id'], ['id'])
    op.drop_column('Request', 'request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Request', sa.Column('request_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Request', type_='foreignkey')
    op.create_foreign_key('Request_request_id_fkey', 'Request', 'Request_type', ['request_id'], ['id'])
    op.drop_column('Request', 'type_id')
    # ### end Alembic commands ###
