"""empty message

Revision ID: 9e6da02c9d17
Revises: 3cb1dbdb6633
Create Date: 2018-06-28 10:02:42.639639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6da02c9d17'
down_revision = '3cb1dbdb6633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Revoked_token', sa.Column('jti', sa.String(), nullable=False))
    op.drop_column('Revoked_token', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Revoked_token', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Revoked_token', 'jti')
    # ### end Alembic commands ###
